### ISSUE TITLE
can't mine cn-pico

### ISSUE THREAD

**Issue by pr0vieh** [MoneroOcean/xmrig#10]
Hi, 

with the new evo/beta xmrig the miner never switch to cn-pico...
also with 999999999999995280 as perf setting for cn-pico !
some algo naming problem ?

```
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "numa": true
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": 0,
        "asm": true,
        "cn": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3]
        ],
        "cn-heavy": [
            [1, 0],
            [1, 1]
        ],
        "cn-lite": [
            [1, 0],
            [1, 4],
            [1, 1],
            [1, 5],
            [1, 2],
            [1, 6],
            [1, 3],
            [1, 7]
        ],
        "cn-pico": [
            [2, 0],
            [2, 4],
            [2, 1],
            [2, 5],
            [2, 2],
            [2, 6],
            [2, 3],
            [2, 7]
        ],
        "cn/gpu": [0, 4, 1, 5, 2, 6, 3, 7],
        "rx": [0, 1, 2, 3],
        "rx/wow": [0, 1, 2, 3],
        "cn/0": false,
        "cn-lite/0": false
    },
    "algo-perf": {
        "cn/1": 279.0,
        "cn/2": 279.0,
        "cn/r": 279.0,
        "cn/wow": 279.0,
        "cn/fast": 540.0,
        "cn/half": 540.0,
        "cn/xao": 241.1,
        "cn/rto": 241.1,
        "cn/rwz": 373.0,
        "cn/zls": 322.1,
        "cn/double": 120.1,
        "cn/gpu": 60.0,
        "cn-lite/1": 1072.0,
        "cn-heavy/0": 93.0,
        "cn-heavy/tube": 108.0,
        "cn-heavy/xhv": 133.0,
        "cn-pico": 999999999999995280.0,
        "rx/test": 2036.1,
        "rx/wow": 2670.0,
        "rx/loki": 2278.0
    },
    "donate-level": 0,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "url": "gulf.moneroocean.stream:10001",
            "user": "user",
            "pass": "pass",
            "rig-id": "name",
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": false,
    "rebench-algo": false,
    "bench-algo-time": 10
}
```

**Comment by setuidroot** [comment]
I need more information to help you... Windows or Linux?  CPU type?  Can you fetch a screenshot from the start of the miner?  (The screenshot will show me your CPU type and pool connections as the miner initializes.)

First up know that Turtle is forking to an Argon2d algo variant at block height of 1.8 million, that is ~18.375 days away from the time of this post.  This is last I heard (maybe Turtle delayed it, but I think not.)  That'd leave only xtendcash on cn-pico.

But that's not why your miner won't switch to cn-pico.  Does the miner work at all (any algo?)  

Change these values in your config.json (by order of appearance):


"autosave": false,

"cn-pico": 21000,

"url": "gulf.moneroocean.stream:10016",

"user": "YoUrWaLLeTaDDreSS",

"rig-id": null,


Here's why: 

1: Turn autosave off so it doesn't change your config file automatically afterwards.

2: Change cn-pico's algo-perf rating to a plausible (yet "more profitable than the others") number; the pool will reject insanely high perf numbers assuming error.  21000 is reasonable and will make pool choose cn-pico regardless of profitability except when cn-pico's daemons are down (then probably mine Monero for a short time.)

3: Raise the starting difficulty port number to not be a big burden on pool node.  cn-pico will produced high hashrate and thus high diff shares; don't spam low (1000) diff cn-pico shares as it hurts everyone ane can get your IP a temp (~5 min) ban and/or (mpre likely) your shares will go through MO's mining proxy and you'll get a 1% fee for using the proxy.  The proxy is temporary once your share diff increases.

4: You need a wallet address, if you don't have one/want a testing one, use this one (donates to pool owner): 44qJYxdbuqSKarYnDSXB6KLbsH4yR65vpJe3ELLDii9i4ZgKpgQXZYR4AMJxBJbfbKZGWUxZU42QyZSsP4AyZZMbJBCrWr1

5: Set your "rig-id": null, (notice there's no quotes around null here.)  This is probably the **most important** step along with step #2.  Why?  **Just do it.**  (lol sorry but true.)  The pool doesn't play nice with rig-id, put your rig's name in the "pass": "NameOfRig", spot.  Set rig-id to null and forget rig-id even exists.

This is comprehensive and should fix whatever your problem is/was.  Hopefully this will help others in the future as well.

**Comment by setuidroot** [comment]
If after all I pointed out above doesn't work for you, the lower your algo-perf for the RandomX algos.  Only do this if the above suggestions didn't work and/or if you don't want your miner to switch to any RandomX algos.

To do this, subtract 2000 from each of the three RandomX algo-perfs:

```
"rx/test": 36.1,
"rx/wow" 670.0,
"rx/loki": 278.0
```

**Comment by pr0vieh** [comment]
thanks for the reply but im not new at this pool... ;)
i have also addressed some of your suggestions but the pool don't give me cn-pico...
"cn/r": 999999999999.0, -> i get xmr from the pool
"cn/half": 999999999999.0, -> i get msr from the pool 
"cn-pico": 999999999999995280.0, will be ignored

```
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": false,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "numa": true
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": 0,
        "asm": true,
        "cn": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3]
        ],
        "cn-heavy": [
            [1, 0],
            [1, 1]
        ],
        "cn-lite": [
            [1, 0],
            [1, 4],
            [1, 1],
            [1, 5],
            [1, 2],
            [1, 6],
            [1, 3],
            [1, 7]
        ],
        "cn-pico": [
            [2, 0],
            [2, 4],
            [2, 1],
            [2, 5],
            [2, 2],
            [2, 6],
            [2, 3],
            [2, 7]
        ],
        "cn/gpu": [0, 4, 1, 5, 2, 6, 3, 7],
        "rx": [0, 1, 2, 3],
        "rx/wow": [0, 1, 2, 3],
        "cn/0": false,
        "cn-lite/0": false
    },
    "algo-perf": {
        "cn/1": 279.0,
        "cn/2": 279.0,
        "cn/r": 279.0,
        "cn/wow": 279.0,
        "cn/fast": 540.0,
        "cn/half": 540.0,
        "cn/xao": 241.1,
        "cn/rto": 241.1,
        "cn/rwz": 373.0,
        "cn/zls": 322.1,
        "cn/double": 120.1,
        "cn/gpu": 60.0,
        "cn-lite/1": 1072.0,
        "cn-heavy/0": 93.0,
        "cn-heavy/tube": 108.0,
        "cn-heavy/xhv": 133.0,
        "cn-pico": 99995280.0,
        "rx/test": 2036.1,
        "rx/wow": 2670.0,
        "rx/loki": 2278.0
    },
    "donate-level": 0,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "url": "gulf.moneroocean.stream:10016",
            "user": "Wallet",
            "pass": "pass",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": false,
    "rebench-algo": false,
    "bench-algo-time": 10
}
```

![image](https://user-images.githubusercontent.com/61424/62834863-38ee6b00-bc52-11e9-9a26-a10b7f35a3e2.png)
```
    "algo-perf": {
        "cn/1": 100.0,
        "cn/2": 100.0,
        "cn/r": 100.0,
        "cn/wow": 100.0,
        "cn/fast": 100.0,
        "cn/half": 100.0,
        "cn/xao": 100.0,
        "cn/rto": 100.0,
        "cn/rwz": 100.0,
        "cn/zls": 100.0,
        "cn/double": 100.0,
        "cn/gpu": 100.0,
        "cn-lite/1": 100.0,
        "cn-heavy/0": 100.0,
        "cn-heavy/tube": 100.0,
        "cn-heavy/xhv": 100.0,
        "cn-pico": 99995280.0,
        "rx/test": 100.0,
        "rx/wow": 100.0,
        "rx/loki": 100.0
    },
```
![image](https://user-images.githubusercontent.com/61424/62834993-ae0e7000-bc53-11e9-8601-37fb00e253fe.png)

greets Pr0vieH

**Comment by setuidroot** [comment]
That's strange.  It's clear to me you know what you're doing.  I'm running the same version of this miner on Ubuntu 18.04 (GCC 7.4.0) without issue and I was able to get cn-pico working on it at first by adjusting the algo-perf to favor it.  I'm mining rx variants now because it's most profitable for my system.

Two things:  

1. Try lowering your "cn-pico": 20000, (or so) with the others all set at 100.  This is because I've noticed the pool seems to work algo-perfs proportionally... if one algo is set too high, out of proportion with the others, the pool (IME) tends to ignore that one.

2. Failing that I'd guess that node you're mining too is having issues with it's Turtle coin daemon at the moment.  You can test this by trying cn-pico to the same node with version 2.13.1 or 2.14 (before any RandomX.)  **Or** you can try a different node like: us.moneroocean.stream and see if it'll give you cn-pico.  

I will test cn-pico on my rig to make sure it's still working (pool says it's up and it has hashrate.)
