### ISSUE TITLE
Mac Release Binary Isn't Working on x86

### ISSUE THREAD

**Issue by a-p-jo** [MoneroOcean/xmrig#140]
**Describe the bug**
When I run `./xmrig` after extracting the latest release `v6.21.3-mo12`, I get `zsh: bad CPU type in executable: ./xmrig`.

**To Reproduce**
Use MacOS. 

**Expected behavior**
It should run just fine.

**Required data**
 - XMRig version
    - https://github.com/MoneroOcean/xmrig/tree/v6.21.3-mo12
 - OS: MacOS Monterey 12.7.5
 - Device: MacBook Air 2017 13" (Intel i5)

**Comment by Spudz76** [comment]
The mac64 release build is for arm64 (M1 and friends), build your own from source.

```
$ tar xvf ../xmrig-v6.21.3-mo12-mac64.tar.gz
xmrig
config.json
$ file xmrig
xmrig: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>
```

**Comment by a-p-jo** [comment]
@Spudz76 Yes, I'm aware it's an ARM binary, and have compiled it myself at the moment. However,  previously I recall there used to be an x86_64 binary for macOS, and it would be highly desirable if that continues to be the case.

**Comment by Spudz76** [comment]
It appears that since the release build has always used `macos-latest` builder image, then the Intel build changed to Arm when GitHub changed "latest" from 13 to 14.  And MacOS 14 is Arm-only?  So it wasn't intentional to abandon Intel but it was a side effect of Apple abandoning it, and "latest" following along.
