### ISSUE TITLE
question: Does it really increase earnings?

### ISSUE THREAD

**Issue by richmailYT** [MoneroOcean/xmrig#84]
I dont see any imporvements mentioned in your release logs, only merges and slight bug fixes. 

From my perspective, XMRig is better

Please exsplain to me how this version of XMRig is better

**Comment by jmakov** [comment]
1 Week ago my nodes were mining XHV, today RPT. The algo was switched in the background automatically. But yes, I'd also be interested in some docs on how the most profitable algo is computed.

**Comment by Spudz76** [comment]
Pool takes TradeOgre prices for each coin and compares 

`(AltcoinPrice * AltcoinHashrate) / XMRPrice = XMREquivalentHashrate`

The highest XMREquivalentHashrate result from checking that against your `algo-perf` list which is sent at login.

If your `algo-perf` is anywhere close to accurate then obviously through the math, you mine whichever thing is currently worth the most for your rig.  It's terribly simple.

**Comment by Jhobean** [comment]
@Spudz76 include watt in calculation could be implement? Maybe add a generic watt or possibility to add value in config.

It should be an important improvement because heavy/xhv use way more watt than other algo.

**Comment by Spudz76** [comment]
You could adjust for watts if you like, by multiplying the `algo-perf` hashrate by the "loss" of watts per algo, after you've collected the watt usage for each.

**Comment by richmailYT** [comment]
this is all pool stuff. whats the fork of XMRig doing?

**Comment by Spudz76** [comment]
* Adds `panthera` and `cn-gpu` algos which are refused upstream (political reasons, who knows)
* Adds `algo-perf` support including the first-run benchmarking routine to generate an `algo-perf`

Pool can't decide which algo you should process, without your `algo-perf`

Not really sure what you're asking since it's all open-source and you could [go look at what's changed yourself](https://github.com/xmrig/xmrig/compare/master...MoneroOcean:master.diff)
